In [1]:
import os 
import pandas as pd
import numpy as np

In [2]:
DATA_FOLDER = './housing_price/data'
df = pd.read_csv(os.path.join(DATA_FOLDER, 'train.csv'))

In [3]:
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [6]:
pd.pivot_table (df,index = ['YrSold','SaleCondition'])

                         1stFlrSF    2ndFlrSF  3SsnPorch  BedroomAbvGr  \
YrSold SaleCondition
2006   Abnorml        1072.969697  245.606061   5.454545      2.848485
       AdjLand         819.000000  263.000000   0.000000      4.500000
       Alloca         1575.000000  626.000000   0.000000      4.000000
       Family         1284.125000  196.500000   0.000000      3.500000
       Normal         1139.299559  361.533040   1.850220      2.845815
       Partial        1322.325581  446.976744   4.441860      2.813953
2007   Abnorml        1286.230769  604.615385   0.000000      3.384615
       AdjLand         756.000000  378.000000   0.000000      3.000000
       Alloca         1862.000000  418.000000   0.000000      3.333333
       Family         1255.428571  398.285714   0.000000      3.285714
       Normal         1146.732075  348.581132   1.962264      2.943396
       Partial        1433.300000  323.725000   0.000000      2.775000
2008   Abnorml        1156.428571  248.904762  10.285714      2.666667
       AdjLand        1152.000000    0.000000   0.000000      2.000000
       Alloca         1301.000000    0.000000   0.000000      1.000000
       Normal         1093.518939  374.227273   4.287879      2.909091
       Partial        1736.812500  237.812500  28.562500      2.500000
2009   Abnorml        1154.869565  298.913043   0.000000      2.739130
       Alloca         1322.800000  224.000000   0.000000      3.800000
       Family         1311.000000    0.000000   0.000000      3.000000
       Normal         1139.000000  343.180556   5.138889      2.777778
       Partial        1417.421053  372.157895   0.000000      2.631579
2010   Abnorml         920.545455  182.636364   0.000000      2.545455
       Alloca         1044.000000    0.000000   0.000000      2.000000
       Family          849.000000  283.500000   0.000000      3.000000
       Normal         1163.798701  333.694805   2.480519      2.922078
       Partial        1615.857143  170.571429   0.000000      2.428571

                       BsmtFinSF1  BsmtFinSF2  BsmtFullBath  BsmtHalfBath  \
YrSold SaleCondition
2006   Abnorml         390.000000  123.636364      0.454545      0.090909
       AdjLand         472.500000    0.000000      0.000000      1.000000
       Alloca            0.000000    0.000000      0.000000      0.000000
       Family          368.250000    0.000000      0.250000      0.000000
       Normal          469.370044   37.215859      0.440529      0.057269
       Partial         380.116279    0.000000      0.348837      0.000000
2007   Abnorml         411.000000  122.461538      0.307692      0.000000
       AdjLand         312.000000    0.000000      1.000000      0.000000
       Alloca          605.000000    0.000000      0.333333      0.000000
       Family          611.285714   78.000000      0.285714      0.285714
       Normal          416.837736   46.441509      0.335849      0.079245
       Partial         330.600000    0.000000      0.300000      0.050000
2008   Abnorml         440.095238   23.476190      0.333333      0.142857
       AdjLand           0.000000    0.000000      0.000000      0.000000
       Alloca         1253.500000    0.000000      2.000000      0.000000
       Normal          431.113636   55.571970      0.458333      0.060606
       Partial        1128.250000   10.562500      0.687500      0.062500
2009   Abnorml         399.391304   56.434783      0.347826      0.086957
       Alloca          457.200000    0.000000      1.000000      0.000000
       Family          274.000000    0.000000      0.000000      0.333333
       Normal          448.708333   45.569444      0.440972      0.052083
       Partial         442.526316    0.000000      0.421053      0.000000
2010   Abnorml         361.090909   11.545455      0.454545      0.090909
       Alloca            0.000000    0.000000      0.000000      0.000000
       Family          442.500000   84.000000      0.500000      0.000000
       Normal          431.383117   71.032468      0.506494      0.012987
       Partial        1113.000000    0.000000      0.714286      0.000000

                        BsmtUnfSF  EnclosedPorch      ...       OverallCond  \
YrSold SaleCondition                                  ...
2006   Abnorml         482.757576      65.303030      ...          5.333333
       AdjLand         329.000000       0.000000      ...          4.000000
       Alloca          697.000000       0.000000      ...          7.000000
       Family          856.375000      56.000000      ...          4.875000
       Normal          504.995595      19.806167      ...          5.537445
       Partial         917.325581       0.860465      ...          5.000000
2007   Abnorml         589.769231      30.615385      ...          5.153846
       AdjLand         444.000000       0.000000      ...          6.000000
       Alloca          697.333333      66.666667      ...          5.333333
       Family          405.285714       0.000000      ...          5.571429
       Normal          575.543396      27.324528      ...          5.683019
       Partial        1095.350000       0.000000      ...          5.075000
2008   Abnorml         585.047619      32.047619      ...          5.761905
       AdjLand           0.000000       0.000000      ...          5.000000
       Alloca           17.500000       0.000000      ...          4.500000
       Normal          504.340909      21.810606      ...          5.818182
       Partial         675.062500       0.000000      ...          5.000000
2009   Abnorml         565.695652      15.521739      ...          5.043478
       Alloca            0.000000       0.000000      ...          5.000000
       Family          915.333333       0.000000      ...          6.000000
       Normal          543.802083      20.152778      ...          5.579861
       Partial         966.526316       5.368421      ...          5.157895
2010   Abnorml         408.909091      44.818182      ...          5.818182
       Alloca          540.000000       0.000000      ...          5.000000
       Family          262.500000       0.000000      ...          5.500000
       Normal          549.006494      25.266234      ...          5.675325
       Partial         495.428571       0.000000      ...          4.571429

                      OverallQual    PoolArea      SalePrice  ScreenPorch  \
YrSold SaleCondition
2006   Abnorml           5.454545   15.515152  142857.363636    20.575758
       AdjLand           5.500000    0.000000  104250.000000     0.000000
       Alloca            6.000000  738.000000  274970.000000     0.000000
       Family            5.000000    0.000000  138500.000000     0.000000
       Normal            6.030837    5.140969  175522.612335    14.185022
       Partial           7.418605    0.000000  259793.813953     2.790698
2007   Abnorml           5.769231   42.692308  198346.153846    11.307692
       AdjLand           5.000000    0.000000  126000.000000     0.000000
       Alloca            6.000000    0.000000  216398.333333     0.000000
       Family            6.142857    0.000000  176142.857143    21.857143
       Normal            5.962264    0.000000  175312.124528    14.562264
       Partial           7.425000    0.000000  254259.225000    20.900000
2008   Abnorml           6.047619    0.000000  154500.000000    18.523810
       AdjLand           4.000000    0.000000   82000.000000     0.000000
       Alloca            5.500000    0.000000  157629.500000     0.000000
       Normal            6.003788    2.181818  172062.556818    17.378788
       Partial           8.187500   30.000000  303213.812500    14.000000
2009   Abnorml           5.434783    0.000000  132692.173913    35.478261
       Alloca            5.000000    0.000000  142622.400000     0.000000
       Family            6.666667    0.000000  131000.000000     0.000000
       Normal            6.048611    0.000000  177025.190972    15.079861
       Partial           7.473684    0.000000  289829.684211    13.263158
2010   Abnorml           5.090909    0.000000  109997.818182     0.000000
       Alloca            5.000000    0.000000   55993.000000     0.000000
       Family            6.500000    0.000000  129000.000000     0.000000
       Normal            5.974026    0.000000  176513.915584    15.344156
       Partial           8.000000    0.000000  333825.857143     0.000000

                      TotRmsAbvGrd  TotalBsmtSF  WoodDeckSF    YearBuilt  \
YrSold SaleCondition
2006   Abnorml            6.090909   996.393939   64.333333  1960.212121
       AdjLand            6.000000   801.500000    0.000000  1942.500000
       Alloca             8.000000   697.000000  586.000000  1966.000000
       Family             7.375000  1224.625000   61.000000  1946.000000
       Normal             6.458150  1011.581498   96.920705  1968.731278
       Partial            7.279070  1297.441860  130.651163  2005.511628
2007   Abnorml            7.384615  1123.230769  116.923077  1959.923077
       AdjLand            7.000000   756.000000    0.000000  1940.000000
       Alloca             8.666667  1302.333333    0.000000  1942.666667
       Family             7.142857  1094.571429  133.857143  1975.142857
       Normal             6.501887  1038.822642   78.124528  1968.105660
       Partial            7.275000  1425.950000  102.150000  2006.475000
2008   Abnorml            5.952381  1048.619048   45.142857  1964.095238
       AdjLand            6.000000     0.000000    0.000000  1955.000000
       Alloca             7.000000  1271.000000   60.000000  1983.000000
       Normal             6.409091   991.026515  100.371212  1967.125000
       Partial            7.187500  1813.875000   67.375000  2003.750000
2009   Abnorml            6.217391  1021.521739   74.869565  1958.695652
       Alloca             7.800000   457.200000   78.800000  1980.600000
       Family             6.000000  1189.333333   64.000000  1967.666667
       Normal             6.388889  1038.079861  100.517361  1970.708333
       Partial            7.105263  1409.052632   83.684211  2001.789474
2010   Abnorml            5.727273   781.545455   80.818182  1945.727273
       Alloca             4.000000   540.000000    0.000000  1952.000000
       Family             6.000000   789.000000    0.000000  1972.500000
       Normal             6.512987  1051.422078  108.324675  1971.194805
       Partial            7.857143  1608.428571   67.571429  2008.571429

                      YearRemodAdd
YrSold SaleCondition
2006   Abnorml         1973.515152
       AdjLand         1985.500000
       Alloca          1966.000000
       Family          1965.500000
       Normal          1980.132159
       Partial         2005.930233
2007   Abnorml         1980.461538
       AdjLand         1950.000000
       Alloca          1991.000000
       Family          1986.142857
       Normal          1983.207547
       Partial         2006.950000
2008   Abnorml         1976.095238
       AdjLand         1955.000000
       Alloca          1983.500000
       Normal          1984.424242
       Partial         2004.375000
2009   Abnorml         1973.086957
       Alloca          1980.800000
       Family          1985.666667
       Normal          1985.479167
       Partial         2008.578947
2010   Abnorml         1971.000000
       Alloca          1952.000000
       Family          1972.500000
       Normal          1985.253247
       Partial         2009.142857

[27 rows x 37 columns]

In [7]:
# Default aggregation method is mean value 
pd.pivot_table (df,index = ['YrSold','SaleCondition'],values = ['SalePrice'])

                          SalePrice
YrSold SaleCondition
2006   Abnorml        142857.363636
       AdjLand        104250.000000
       Alloca         274970.000000
       Family         138500.000000
       Normal         175522.612335
       Partial        259793.813953
2007   Abnorml        198346.153846
       AdjLand        126000.000000
       Alloca         216398.333333
       Family         176142.857143
       Normal         175312.124528
       Partial        254259.225000
2008   Abnorml        154500.000000
       AdjLand         82000.000000
       Alloca         157629.500000
       Normal         172062.556818
       Partial        303213.812500
2009   Abnorml        132692.173913
       Alloca         142622.400000
       Family         131000.000000
       Normal         177025.190972
       Partial        289829.684211
2010   Abnorml        109997.818182
       Alloca          55993.000000
       Family         129000.000000
       Normal         176513.915584
       Partial        333825.857143

In [10]:
# Using mean and len to get a count 
pd.pivot_table (df,index = ['YrSold','SaleCondition'],values = ['SalePrice'],aggfunc=[np.median,len])

                        median       len
                     SalePrice SalePrice
YrSold SaleCondition
2006   Abnorml        130000.0        33
       AdjLand        104250.0         2
       Alloca         274970.0         1
       Family         135000.0         8
       Normal         159500.0       227
       Partial        232600.0        43
2007   Abnorml        150000.0        13
       AdjLand        126000.0         1
       Alloca         200624.0         3
       Family         136000.0         7
       Normal         156000.0       265
       Partial        233437.5        40
2008   Abnorml        140000.0        21
       AdjLand         82000.0         1
       Alloca         157629.5         2
       Normal         162950.0       264
       Partial        316413.5        16
2009   Abnorml        125000.0        23
       Alloca         142953.0         5
       Family         152000.0         3
       Normal         162750.0       288
       Partial        252678.0        19
2010   Abnorml        107000.0        11
       Alloca          55993.0         1
       Family         129000.0         2
       Normal         156450.0       154
       Partial        269500.0         7

In [12]:
# Further segragating using column 
# fill_value to deal with NaN problem
pd.pivot_table (df,index = ['YrSold','SaleCondition'],
                columns = ['Utilities'],values = ['SalePrice'],
                aggfunc=[np.median,len],fill_value = 0)

                        median               len
                     SalePrice         SalePrice
Utilities               AllPub  NoSeWa    AllPub NoSeWa
YrSold SaleCondition
2006   Abnorml        130000.0       0        33      0
       AdjLand        104250.0       0         2      0
       Alloca         274970.0       0         1      0
       Family         135000.0       0         8      0
       Normal         159500.0       0       227      0
       Partial        232600.0       0        43      0
2007   Abnorml        150000.0       0        13      0
       AdjLand        126000.0       0         1      0
       Alloca         200624.0       0         3      0
       Family         136000.0       0         7      0
       Normal         156000.0       0       265      0
       Partial        233437.5       0        40      0
2008   Abnorml        140000.0       0        21      0
       AdjLand         82000.0       0         1      0
       Alloca         157629.5       0         2      0
       Normal         162950.0       0       264      0
       Partial        316413.5       0        16      0
2009   Abnorml        118500.0  137500        22      1
       Alloca         142953.0       0         5      0
       Family         152000.0       0         3      0
       Normal         162750.0       0       288      0
       Partial        252678.0       0        19      0
2010   Abnorml        107000.0       0        11      0
       Alloca          55993.0       0         1      0
       Family         129000.0       0         2      0
       Normal         156450.0       0       154      0
       Partial        269500.0       0         7      0

In [13]:
# The result is still a DataFrame

table = pd.pivot_table (df,index = ['YrSold','SaleCondition'],
                columns = ['Utilities'],values = ['SalePrice'],
                aggfunc=[np.median,len],fill_value = 0)

In [18]:
# Only look at certain SaleCondition
table.query('SaleCondition == ["Normal","Family"]')

                        median              len
                     SalePrice        SalePrice
Utilities               AllPub NoSeWa    AllPub NoSeWa
YrSold SaleCondition
2006   Family         135000.0      0         8      0
       Normal         159500.0      0       227      0
2007   Family         136000.0      0         7      0
       Normal         156000.0      0       265      0
2008   Normal         162950.0      0       264      0
2009   Family         152000.0      0         3      0
       Normal         162750.0      0       288      0
2010   Family         129000.0      0         2      0
       Normal         156450.0      0       154      0